version: '3'

services:
  frontend:
    build: 
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      MONGO_URI: mongodb://database:27017/myapp
    depends_on:
      - database

  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: database
      
volumes:
  mongo_data:
    driver: local
