name: Build Dockerfile

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "nitin03" --password-stdin
        cd frontend
        docker image build --file Dockerfile.frontend -t nitin03/remotecofrontend:latest .
        docker push nitin03/remotecofrontend:latest
        cd ..
        docker image build --file Dockerfile.backend -t nitin03/remotecobackend:latest .
        docker push nitin03/remotecobackend:latest
